# Site settings
# in the templates available like {{ site.myvariable }}.
title: Home Page
email: skyshu@yeah.net
brand: 张 天
headline: University Student
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: skyshu@yeah.net
phone: petite_sky

# Tracking
googleAnalitycsID: UA-83933844-1

